import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

// Type-aware linting is deliberately NOT enabled. `npm run typecheck` already
// runs tsc over the same tree in the same gate, so the type-checked rule set
// would mostly re-report what tsc has already failed on, at several times the
// runtime. eslint's job here is the class of bug tsc cannot see: unused vars,
// bad hook dependencies, `case` blocks that leak declarations.
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "target/**",
      "node_modules/**",
      // rustdoc output.
      "doc/**",
      // ts-rs generated, in all three places it lands: the committed bindings
      // (`shared/types/`), the per-crate intermediate output
      // (`crates/*/bindings/`), and the staging dir generate-bindings.sh uses.
      // Linting output we do not author would only ever produce findings we
      // cannot fix at the source — every one of these files carries a
      // "Do not edit this file manually" header.
      "**/shared/types/**",
      "crates/*/bindings/**",
      ".bindings-stage.*/**",
      "site/assets/**",
      "coverage/**",
      // Dot-directories are local tool and editor state, never project
      // sources. Some of them hold whole secondary checkouts, so walking
      // them would lint the repo several times over and report findings
      // against unrelated branches.
      "**/.*/**",
    ],
  },

  // Catch-all — MUST come first so the specific blocks below refine it.
  //
  // ESLint 9 flat config has no implicit "lint everything except ignores".
  // A file matching no `files:` glob is silently skipped: `eslint .` walks
  // past it, reports nothing, and exits 0. That leaves every new top-level
  // directory unlinted by default with no signal whatsoever — which is how a
  // lint quietly becomes a no-op again, the exact failure this config exists
  // to prevent. This block guarantees a floor: new code is linted the day it
  // lands, and adding a tailored block for it is an improvement rather than a
  // prerequisite.
  //
  // It carries the TypeScript parser too. Without that, a `.ts` file outside
  // `src/` fails with "Parsing error: Unexpected token" instead of being
  // linted — a floor that only reports parse errors is not a floor.
  {
    files: ["**/*.{js,mjs,cjs,ts,tsx}"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: { ecmaVersion: 2022, sourceType: "module" },
    rules: {
      // Repo-wide conventions, set here so they hold for code that has no
      // block of its own yet.
      //
      // The codebase uses a leading underscore to mark a deliberately unused
      // binding — most often an ignored destructured field or a catch param.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
          destructuredArrayIgnorePattern: "^_",
        },
      ],
      // A `case` carrying only a comment is still an empty case. Without
      // this, `src/ipc/error.ts` reports a fallthrough for a group of five
      // codes that all return the same expression, where the comment
      // explains why one of them keeps its message. The rule still errors on
      // a case with real statements, which is the bug worth catching.
      "no-fallthrough": ["error", { allowEmptyCase: true }],
    },
  },

  // Desktop client sources.
  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // Off by choice, not by accident. This is a dev-server ergonomics hint
      // (fast refresh degrades to a full reload when a module exports a
      // component *and* something else), not a correctness rule, and ~14
      // files here deliberately colocate a helper or constant with the
      // component that uses it. Left installed so it can be flipped to
      // "warn" if HMR ever feels broken.
      "react-refresh/only-export-components": "off",
    },
  },

  // The landing page: plain browser JS, no build step, no TypeScript. It had
  // no gate coverage at all before this — `pages.yml` deploys it and nothing
  // checked it, so a syntax error or a typo'd identifier shipped silently.
  // It is a top-level IIFE loaded via a plain <script defer>, hence "script"
  // rather than "module".
  {
    files: ["site/**/*.js"],
    languageOptions: {
      sourceType: "script",
      globals: globals.browser,
    },
  },

  // Build/tool config that runs in Node, not the browser.
  {
    files: ["*.config.{js,ts}", "scripts/**/*.{js,mjs}"],
    languageOptions: { globals: globals.node },
  },
);
