import { act, cleanup, renderHook } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { useVideoPlan } from "../useVideoPlan";
import type { ConvertRequest, VideoExecutionSummary } from "@/types";
const plan = vi.hoisted(() => vi.fn());
vi.mock("@/ipc/commands", () => ({api:{convert:{videoPlan:plan}}}));
afterEach(() => { cleanup(); vi.useRealTimers(); vi.clearAllMocks(); });
const request: ConvertRequest = {input_path:"/a.mp4",output_path:"",target:"mp4",video_options:{kind:"copy"},quality_preset:null,resolution_cap:null,compress_mode:null,metadata_policy:"preserve",subtitle:null,gif_options:null,batch_id:null};
const summary: VideoExecutionSummary = {requested:{kind:"copy"},video_codec:"h264",video_stream_index:0,audio_copied:false,width:1920,height:1080,notices:[]};
it("debounces, keeps only the latest pending request, and discards stale replies", async () => {
  vi.useFakeTimers();
  const resolvers: ((v:VideoExecutionSummary)=>void)[] = [];
  plan.mockImplementation(() => new Promise(resolve => resolvers.push(resolve)));
  const view = renderHook(({req}) => useVideoPlan(req), {initialProps:{req:request as ConvertRequest|null}});
  await act(async () => vi.advanceTimersByTime(300));
  expect(plan).toHaveBeenCalledTimes(1);
  view.rerender({req:{...request,input_path:"/b.mp4"}});
  await act(async () => vi.advanceTimersByTime(300));
  view.rerender({req:{...request,input_path:"/c.mp4"}});
  await act(async () => vi.advanceTimersByTime(300));
  expect(plan).toHaveBeenCalledTimes(1);
  await act(async () => resolvers[0](summary));
  expect(view.result.current.summary).toBeNull();
  expect(plan).toHaveBeenCalledTimes(2);
  expect(plan.mock.calls[1][0].input_path).toBe("/c.mp4");
  await act(async () => resolvers[1]({...summary,width:640}));
  expect(view.result.current.summary?.width).toBe(640);
  view.rerender({req:null});
  expect(view.result.current.summary).toBeNull();
});
it("retains the native concurrency slot across route retirement and remount", async () => {
  vi.useFakeTimers();
  const resolvers: ((v:VideoExecutionSummary)=>void)[] = [];
  plan.mockImplementation(() => new Promise(resolve => resolvers.push(resolve)));
  const first = renderHook(() => useVideoPlan(request));
  await act(async () => vi.advanceTimersByTime(300));
  first.unmount();
  const next = renderHook(() => useVideoPlan({...request,input_path:"/new.mp4"}));
  await act(async () => vi.advanceTimersByTime(300));
  expect(plan).toHaveBeenCalledTimes(1);
  await act(async () => resolvers[0](summary));
  expect(plan).toHaveBeenCalledTimes(2);
  expect(next.result.current.summary).toBeNull();
  await act(async () => resolvers[1](summary));
  expect(next.result.current.summary).toEqual(summary);
});
it("does not resurrect an old successful plan when returning to a previous request", async () => {
  vi.useFakeTimers(); plan.mockResolvedValue(summary);
  const view = renderHook(({req}) => useVideoPlan(req), {initialProps:{req:request}});
  await act(async () => vi.advanceTimersByTime(300));
  expect(view.result.current.summary).toEqual(summary);
  view.rerender({req:{...request,input_path:"/b.mp4"}});
  view.rerender({req:request});
  expect(view.result.current.summary).toBeNull();
  await act(async () => vi.advanceTimersByTime(300));
});
it("debounces edits before native work and discards retired errors", async () => {
  vi.useFakeTimers();
  let reject!: (error:Error)=>void;
  plan.mockImplementationOnce(() => new Promise((_resolve, fail) => {reject=fail;})).mockResolvedValue(summary);
  const view = renderHook(({req}) => useVideoPlan(req), {initialProps:{req:request}});
  await act(async () => vi.advanceTimersByTime(100));
  view.rerender({req:{...request,input_path:"/b.mp4"}});
  await act(async () => vi.advanceTimersByTime(100));
  expect(plan).not.toHaveBeenCalled();
  await act(async () => vi.advanceTimersByTime(150));
  expect(plan).toHaveBeenCalledTimes(1);
  view.rerender({req:{...request,input_path:"/c.mp4"}});
  await act(async () => vi.advanceTimersByTime(250));
  await act(async () => reject(new Error("Retired source failed")));
  expect(view.result.current.error).toBeNull();
  expect(view.result.current.summary).toEqual(summary);
});
