// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The transfer function used to composite transparent source pixels.
 */
export type AlphaCompositing = "linear_srgb";
