// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an explicit alpha policy can execute for a source-bound target.
 */
export type AlphaPolicyAvailability = { available: boolean, reason: string | null, summary: string, };
