// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioBitrate } from "./AudioBitrate";
import type { AudioChannels } from "./AudioChannels";
import type { AudioSampleRate } from "./AudioSampleRate";

export type AudioConvertOptions = { "kind": "copy" } | { "kind": "encode", bitrate?: AudioBitrate | null, channels: AudioChannels, sample_rate: AudioSampleRate, };
