// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioConvertOptions } from "./AudioConvertOptions";

export type AudioExecutionSummary = { requested: AudioConvertOptions, encoder?: string | null, codec: string, audio_stream_index: number, copied: boolean, sample_rate_hz: number, channels: number, channel_layout?: string | null, sample_format?: string | null, bit_depth?: number | null, reported_bitrate_kbps?: number | null, notices: Array<string>, };
