// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioStreamInfo } from "./AudioStreamInfo";

export type AudioProbeDetails = { streams: Array<AudioStreamInfo>, has_non_audio_streams: boolean, };
