// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioNumericFact } from "./AudioNumericFact";
import type { VideoRationalFact } from "./VideoRationalFact";

export type AudioStreamInfo = { index: number, codec_name?: string | null, sample_rate_hz?: AudioNumericFact | null, channels?: AudioNumericFact | null, channel_layout?: string | null, sample_format?: string | null, bits_per_raw_sample?: AudioNumericFact | null, bit_rate_bps?: AudioNumericFact | null, time_base?: VideoRationalFact | null, start_time_ms?: number, duration_ms?: number, };
