// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioChannels } from "./AudioChannels";
import type { AudioModeAvailability } from "./AudioModeAvailability";
import type { AudioSampleRate } from "./AudioSampleRate";
import type { AudioStreamInfo } from "./AudioStreamInfo";

export type AudioSettingsCapabilities = { copy: AudioModeAvailability, encode: AudioModeAvailability, target_codec: string, encoder: string, bitrate_choices_kbps: Array<number>, default_bitrate_kbps?: number | null, channel_choices: Array<AudioChannels>, default_channels?: AudioChannels | null, sample_rate_choices: Array<AudioSampleRate>, default_sample_rate?: AudioSampleRate | null, source?: AudioStreamInfo | null, };
