// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Editable audio tag fields. Mirrors `PdfMetadata`'s convention: `None` =
 * "leave existing value untouched", `Some("")` = "clear this field",
 * `Some(s)` = "set to s". `track`/`disc`/`year` are carried as strings for a
 * uniform clear/untouch semantics; the writer parses them to numbers.
 */
export type AudioTags = { title: string | null, artist: string | null, album: string | null, album_artist: string | null, track: string | null, disc: string | null, year: string | null, genre: string | null, comment: string | null, composer: string | null, };
