// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChecksumAlgo } from "./ChecksumAlgo";

/**
 * A user-provided expected hash for a direct download. `hex` is compared
 * case-insensitively (whitespace trimmed) against the digest of the
 * streamed bytes.
 */
export type ChecksumSpec = { algo: ChecksumAlgo, hex: string, };
