// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hash algorithm for an optional direct-download integrity check.
 */
export type ChecksumAlgo = "sha256" | "sha1" | "md5";
