// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether one explicit color policy can be applied to an inspected source
 * and target, plus the engine-owned explanation shown by clients.
 */
export type ColorPolicyAvailability = { available: boolean, reason: string | null, summary: string, };
