// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CompressionCapabilities = { quality: boolean, target_size: boolean, lossless: boolean, reason: string | null, };
