// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the Compress tab should reduce a file's size.
 *
 * `Quality` maps a 1..=100 slider to codec-specific parameters (CRF, audio
 * bitrate, JPEG/WebP quality). `LosslessReoptimize` is the PNG-only path
 * that re-saves with max deflate. `TargetSizeBytes` asks for a specific
 * output size in bytes (video/audio via bitrate math, images via iterative
 * quality search).
 */
export type CompressMode = { "kind": "quality", "value": number } | { "kind": "lossless_reoptimize" } | { "kind": "target_size_bytes", "value": bigint };
