// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressMode } from "./CompressMode";
import type { MetadataPolicy } from "./MetadataPolicy";

/**
 * Measured compression outcome. Image target-size execution fills every
 * measurement from the same final metadata-bearing candidate it publishes.
 */
export type CompressionExecution = { requested_mode: CompressMode, attempts: number, selected_quality?: number | null, target_bytes?: bigint | null, final_bytes: bigint, target_met: boolean, metadata_policy: MetadataPolicy, };
