// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressionCapabilities } from "./CompressionCapabilities";
import type { TargetCapability } from "./TargetCapability";

export type ConversionCapabilities = { targets: Array<TargetCapability>, compression: CompressionCapabilities, };
