// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressMode } from "./CompressMode";
import type { GifOptions } from "./GifOptions";
import type { QualityPreset } from "./QualityPreset";
import type { ResolutionCap } from "./ResolutionCap";
import type { TargetFormat } from "./TargetFormat";

export type ConvertRequest = { input_path: string, output_path: string, target: TargetFormat, quality_preset: QualityPreset | null, resolution_cap: ResolutionCap | null, gif_options: GifOptions | null, compress_mode: CompressMode | null, batch_id: string | null, };
