// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetFormat } from "./TargetFormat";

export type ConvertRequest = { input_path: string, output_path: string, target: TargetFormat, };
