// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoExecutionSummary } from "./VideoExecutionSummary";

export type ConvertResult = { video_execution?: VideoExecutionSummary | null, source_bytes?: bigint | null, target_bytes?: bigint | null, output_path: string, bytes: bigint, duration_ms: bigint, reencoded: boolean, };
