// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConversionCapabilities } from "./ConversionCapabilities";
import type { ProbeResult } from "./ProbeResult";
import type { TrackSourceBinding } from "./TrackSourceBinding";

/**
 * A single source read and the capabilities derived from that exact probe.
 */
export type ConversionInspection = { probe: ProbeResult, capabilities: ConversionCapabilities, track_source?: TrackSourceBinding | null, track_source_unavailable_reason?: string | null, };
