// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Embedded cover art as surfaced to the UI. `base64` is the raw image bytes
 * base64-encoded (no data-URL prefix); the frontend builds
 * `data:{mime_type};base64,{base64}`.
 */
export type CoverArt = { mime_type: string, base64: string, };
