// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do with a file's embedded cover art on write. `Keep` leaves it
 * untouched; `Replace` embeds the image at `source_path` as the front cover;
 * `Remove` strips all embedded pictures.
 */
export type CoverArtOp = { "kind": "keep" } | { "kind": "replace", source_path: string, } | { "kind": "remove" };
