// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pixel-space rectangle for `ImageOperation::Crop`. Coordinates are in
 * source image pixels with the origin at the top-left of the image.
 * `width` and `height` must be positive; the backend clamps to image
 * bounds before invoking `DynamicImage::crop_imm`.
 */
export type CropRect = { x: number, y: number, width: number, height: number, };
