// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Probe metadata for a debrid-routed link. Sibling of `DirectFileInfo`
 * for the "via TorBox" card.
 */
export type DebridProbeInfo = { 
/**
 * `true` for magnet links, `false` for hoster links.
 */
magnet: boolean, };
