// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a plain file the extractors don't handle, surfaced by the
 * probe step so the UI can offer a direct download. Populated via an HTTP
 * `HEAD` (or ranged `GET`) by `crate::direct::probe`.
 */
export type DirectFileInfo = { filename: string, size_bytes: bigint | null, content_type: string | null, 
/**
 * `true` when the server advertised `Accept-Ranges: bytes`, so an
 * interrupted download can resume.
 */
resumable: boolean, };
