// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractRequest = { url: string, output_dir: string, format: string | null, audio_only: boolean, 
/**
 * When set, yt-dlp is invoked with `--cookies-from-browser <name>`
 * so it can reuse the user's existing browser session for sites that
 * require login (Twitter/X, Instagram, etc.). Validated against
 * `goop_config::SUPPORTED_BROWSERS` at the IPC boundary; unrecognised
 * values are dropped to `None`.
 */
cookies_from_browser: string | null, };
