// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractRequest = { url: string, output_dir: string, format: string | null, audio_only: boolean, };
