// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How URL extracts should be named on disk. Maps to a yt-dlp output
 * template at the IPC boundary; the frontend never sees the template
 * syntax.
 */
export type ExtractNamingScheme = "title" | "title_site" | "date_title";
