// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtractRequest = { url: string, output_dir: string, format: string | null, audio_only: boolean, 
/**
 * When set, yt-dlp is invoked with `--cookies-from-browser <name>`
 * so it can reuse the user's existing browser session for sites that
 * require login (Twitter/X, Instagram, etc.). Validated against
 * `goop_config::SUPPORTED_BROWSERS` at the IPC boundary; unrecognised
 * values are dropped to `None`.
 */
cookies_from_browser: string | null, 
/**
 * yt-dlp output template fragment (no directory prefix), e.g.
 * `"%(title)s.%(ext)s"`. Resolved from the user's naming-scheme
 * setting at the IPC boundary; `None` falls back to yt-dlp's default.
 * Validated against a known-template allowlist before reaching argv
 * to keep a stale or tampered payload from injecting arbitrary args.
 */
output_template: string | null, 
/**
 * Hint, set by the probe step, that the URL is a plain file neither
 * extractor handles. Lets `dispatch` skip the two doomed extractor
 * spawns and go straight to the direct downloader. Defaults to
 * `false`; the dispatch-level no-match fallback still covers the
 * un-hinted case, so this is purely an optimisation.
 */
direct: boolean, };
