// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which extractor backend handles this URL by default.
 *
 * `YtDlp` is the default for video/audio sites yt-dlp covers natively.
 * `GalleryDl` is preferred for image hosts and for Twitter/X (gallery-dl
 * handles both image+video tweet media via its native extractor; yt-dlp
 * covers single-video edge cases via the dispatcher's fallback).
 *
 * `dispatch::run()` reads this and falls back to the other backend if
 * the chosen one returns a "no matching extractor" error — both
 * directions of fallback are supported.
 */
export type ExtractorChoice = "yt_dlp" | "gallery_dl";
