// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormatOption = { format_id: string, ext: string, resolution: string | null, filesize: bigint | null, is_audio_only: boolean, 
/**
 * The yt-dlp `-f` expression that actually downloads this format,
 * which is not always the bare id. Video-only formats (every YouTube
 * stream above 720p is one) need `+bestaudio` or the file arrives
 * silent, so the selector is composed here rather than in the UI:
 * yt-dlp's format-selector grammar belongs with the rest of the
 * yt-dlp knowledge, and callers can pass it straight through.
 */
selector: string, };
