// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FormatOption = { format_id: string, ext: string, resolution: string | null, filesize: bigint | null, is_audio_only: boolean, };
