// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GifSizePreset } from "./GifSizePreset";

export type GifOptions = { size_preset: GifSizePreset, trim_start_ms: bigint | null, trim_end_ms: bigint | null, };
