// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Columns the History page can sort by. Date sorts on `finished_at`,
 * Size on `result.bytes`, Name on the output file's basename.
 */
export type HistorySort = "date" | "size" | "name";
