// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted preference for how the History page renders. Lives in Settings
 * so the choice survives app restarts.
 */
export type HistoryViewMode = "list" | "grid";
