// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts per `JobKind` plus a grand total; drives the History filter
 * chips' badges so they reflect the current search without extra
 * round-trips.
 */
export type HistoryCounts = { all: number, extract: number, convert: number, pdf: number, };
