// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistorySort } from "./HistorySort";
import type { JobKind } from "./JobKind";

/**
 * Filter passed to `QueueStore::list_terminal` — pushes all filtering to
 * SQL rather than walking the in-memory job list, which matters once
 * users accumulate hundreds of rows.
 */
export type HistoryFilter = { search: string | null, kind: JobKind | null, sort: HistorySort, descending: boolean, };
