// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Target platform set for `ImageOperation::AppIcon`. Backend produces
 * the appropriate container per selection:
 * * `Macos` → `.icns` (Apple icon container)
 * * `Windows` → `.ico` (Windows icon container)
 * * `Web` → loose PNG files at standard favicon sizes
 */
export type IconPlatform = "macos" | "windows" | "web";
