// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageSampleKind } from "./ImageSampleKind";

export type ImagePreviewDetails = { sample_kind: ImageSampleKind, admitted_sample_width: number, admitted_sample_height: number, comparison_frame_width: number, comparison_frame_height: number, planned_output_width: number, planned_output_height: number, current_jpeg_quality: number, pinned_jpeg_quality?: number | null, pinned_path?: string | null, };
