// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit image color behavior. `Preserve` and an absent request field keep
 * the legacy pixel and metadata paths unchanged.
 */
export type ImageColorPolicy = "preserve" | "convert_to_srgb" | "assume_srgb";
