// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the completed image output represents color. These values describe
 * verified handling, not perceptual equivalence between viewers.
 */
export type ImageColorHandling = "exact_profile_retained" | "renderer_sdr_srgb" | "untagged" | "no_profile";
