// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageColorPolicy } from "./ImageColorPolicy";

export type ImageSettingsCapabilities = {
/**
 * Exact managed-color choice required when these settings use a source-bound path.
 */
required_color_policy?: ImageColorPolicy | null, available: boolean, reason: string | null, quality_min: number, quality_max: number, default_quality: number, max_dimension: number, max_output_pixels: number, fit_within: boolean, upscale: boolean, preview_original_available: boolean, preview_fit_within: boolean, preview_unavailable_reason: string | null, };
