// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColorPolicyAvailability } from "./ColorPolicyAvailability";

export type ImageColorCapabilities = { preserve: ColorPolicyAvailability, convert_to_srgb: ColorPolicyAvailability, assume_srgb: ColorPolicyAvailability, };
