// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CropRect } from "./CropRect";
import type { IconPlatform } from "./IconPlatform";
import type { ResizeMode } from "./ResizeMode";
import type { RotationDegrees } from "./RotationDegrees";
import type { WatermarkSpec } from "./WatermarkSpec";

/**
 * What to do with an image. Parallel to `PdfOperation`. The wire shape
 * uses `#[serde(tag = "kind", rename_all = "snake_case")]` so frontend
 * builders emit `{ kind: "rotate", ... }` payloads directly.
 */
export type ImageOperation = { "kind": "rotate", input: string, degrees: RotationDegrees, output_path: string, } | { "kind": "resize", input: string, width: number, height: number, mode: ResizeMode, output_path: string, } | { "kind": "crop", input: string, rect: CropRect, output_path: string, } | { "kind": "watermark", input: string, spec: WatermarkSpec, output_path: string, } | { "kind": "recompress", inputs: Array<string>, output_dir: string, quality: number, } | { "kind": "app_icon", input: string, output_dir: string, platforms: Array<IconPlatform>, };
