// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageResize } from "./ImageResize";

export type ImageConvertOptions = { jpeg_quality: number, resize: ImageResize, };
