// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFormatSupport } from "./ImageFormatSupport";

/**
 * Decoder status summary surfaced in Settings → Image Formats. The
 * version strings reflect the pinned dependency versions at build
 * time; goop bundles the C libs and doesn't ask the user to
 * install anything, so these are read-only.
 */
export type ImageDecoderStatus = { 
/**
 * jpegxl-rs / libjxl versions (libjxl 0.11 built from vendored
 * source via jpegxl-rs's `vendored` feature — statically linked
 * into goop's binary, identical across all release targets).
 */
libjxl_version: string, 
/**
 * Bundled font for watermark rasterization.
 */
watermark_font: string, 
/**
 * Per-format support rows.
 */
formats: Array<ImageFormatSupport>, };
