// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SrgbColor } from "./SrgbColor";

/**
 * Explicit authorization to remove image transparency for an opaque output.
 */
export type ImageAlphaPolicy = { "kind": "flatten", background: SrgbColor, };
