// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageColorHandling } from "./ImageColorHandling";
import type { MetadataPolicy } from "./MetadataPolicy";

/**
 * Verified metadata outcome for a completed image conversion.
 */
export type ImageMetadataExecution = { requested_policy: MetadataPolicy, exif_retained: boolean, icc_retained: boolean, orientation_normalized: boolean, color_handling: ImageColorHandling, notices: Array<string>, };
