// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Source orientation state established by bounded metadata inspection.
 */
export type ImageOrientationStatus = "uninspected" | "absent" | "valid" | "malformed" | "ambiguous";
