// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlphaCompositing } from "./AlphaCompositing";
import type { ImageAlphaPolicy } from "./ImageAlphaPolicy";
import type { SrgbColor } from "./SrgbColor";

/**
 * Verified transparency outcome for a completed conversion.
 */
export type ImageAlphaExecution = { requested_policy: ImageAlphaPolicy, source_had_alpha: boolean, flattened: boolean, background: SrgbColor, compositing: AlphaCompositing, };
