// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlphaPolicyAvailability } from "./AlphaPolicyAvailability";
import type { ImageColorPolicy } from "./ImageColorPolicy";
import type { SrgbColor } from "./SrgbColor";

/**
 * Source-bound transparency facts and explicit policies for an image target.
 */
export type ImageAlphaCapabilities = { source_has_alpha?: boolean | null, flatten: AlphaPolicyAvailability, required_color_policy?: ImageColorPolicy | null, suggested_background: SrgbColor, };
