// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageColorHandling } from "./ImageColorHandling";
import type { ImageColorPolicy } from "./ImageColorPolicy";
import type { MetadataPolicy } from "./MetadataPolicy";

/**
 * Verified metadata outcome for a completed image conversion.
 */
export type ImageMetadataExecution = { requested_policy: MetadataPolicy, requested_color_policy: ImageColorPolicy, exif_retained: boolean, icc_retained: boolean, destination_srgb_profile_attached: boolean, orientation_normalized: boolean, color_handling: ImageColorHandling, notices: Array<string>, };
