// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageOrientationStatus } from "./ImageOrientationStatus";
import type { MetadataPolicyAvailability } from "./MetadataPolicyAvailability";

/**
 * Metadata policy availability and source facts for one image target.
 */
export type ImageMetadataCapabilities = { preserve: MetadataPolicyAvailability, remove_personal: MetadataPolicyAvailability, strip_all: MetadataPolicyAvailability, source_has_exif?: boolean | null, source_has_icc?: boolean | null, orientation: ImageOrientationStatus, };
