// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read-only support row for the Image Formats Settings section.
 * Mirrors the v0.2.4 `LanguagePack` shape so the section can reuse
 * the OcrLanguagesSection visual layout.
 */
export type ImageFormatSupport = { 
/**
 * Human label (e.g. "HEIC / HEIF", "JPEG-XL").
 */
label: string, 
/**
 * File extensions this row covers (e.g. `["heic", "heif"]`).
 */
extensions: Array<string>, 
/**
 * Free-form provenance string (e.g. "libheif 1.21", "image crate
 * 0.25 feature: avif"). Surfaced as a small caption under the
 * label so the user can confirm the format is bundled.
 */
provenance: string, 
/**
 * Whether this row covers decode, encode, or both.
 */
capability: string, };
