// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output kind for `PdfOperation::ImageOcr`. Drives whether the tesseract
 * pipeline produces a `.txt` (text) or a multi-page searchable PDF
 * (searchable_pdf) from the supplied image inputs.
 */
export type ImageOcrOutput = "text" | "searchable_pdf";
