// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFormatSupport } from "./ImageFormatSupport";

/**
 * Decoder status summary surfaced in Settings → Image Formats. The
 * version strings reflect the pinned dependency versions at build
 * time; goop bundles all decoders statically and doesn't ask the
 * user to install anything, so these are read-only.
 */
export type ImageDecoderStatus = { 
/**
 * Bundled font for watermark rasterization.
 */
watermark_font: string, 
/**
 * Per-format support rows.
 */
formats: Array<ImageFormatSupport>, 
/**
 * Free-form line about formats that are coming but not yet
 * shipped. Surfaced below the table in the Settings UI.
 */
coming_soon: string, };
