// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serializable error surface for Tauri IPC.
 */
export type IpcError = { "code": "sidecar_missing", "message": string } | { "code": "subprocess_failed", "message": string } | { "code": "queue", "message": string } | { "code": "config", "message": string } | { "code": "cancelled" } | { "code": "unknown", "message": string };
