// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultKind } from "./ResultKind";

export type JobResult = { output_path: string | null, bytes: bigint | null, duration_ms: bigint, 
/**
 * Defaults to `File` for backward compatibility with existing rows
 * that pre-date the gallery-dl folder-result variant.
 */
result_kind: ResultKind, 
/**
 * Number of files produced. `1` for `File` results; `N` for
 * `Folder` results. Defaults to `1` for backward compatibility.
 */
file_count: number, };
