// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioExecutionSummary } from "./AudioExecutionSummary";
import type { CompressionExecution } from "./CompressionExecution";
import type { ImageMetadataExecution } from "./ImageMetadataExecution";
import type { ResultKind } from "./ResultKind";
import type { TrackExecutionSummary } from "./TrackExecutionSummary";
import type { VideoExecutionSummary } from "./VideoExecutionSummary";
import type { VideoTrackExecutionSummary } from "./VideoTrackExecutionSummary";

export type JobResult = { video_execution?: VideoExecutionSummary | null, source_bytes?: bigint | null, target_bytes?: bigint | null, reencoded?: boolean | null, output_path: string | null, bytes: bigint | null, duration_ms: bigint, 
/**
 * Defaults to `File` for backward compatibility with existing rows
 * that pre-date the gallery-dl folder-result variant.
 */
result_kind: ResultKind, 
/**
 * Number of files produced. `1` for `File` results; `N` for
 * `Folder` results. Defaults to `1` for backward compatibility.
 */
file_count: number, audio_execution?: AudioExecutionSummary | null, track_execution?: TrackExecutionSummary | null, video_track_execution?: VideoTrackExecutionSummary | null, image_metadata_execution?: ImageMetadataExecution | null, compression_execution?: CompressionExecution | null, };
