// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobResult = { output_path: string | null, bytes: bigint | null, duration_ms: bigint, };
