// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobState = "queued" | "running" | "paused" | "done" | { "error": { message: string, } } | "cancelled";
