// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LanguagePack = { 
/**
 * Tesseract language code, e.g. `"eng"`, `"fra"`, `"chi_sim"`.
 */
code: string, 
/**
 * Human-readable label for Settings → OCR Languages.
 */
display_name: string, 
/**
 * Size in bytes. For installed packs this is the on-disk file size;
 * for available-only packs this is the approximate catalog estimate.
 */
size_bytes: bigint, 
/**
 * True when `<code>.traineddata` exists in at least one search dir.
 */
installed: boolean, 
/**
 * True when the pack is bundled with the installer and cannot be
 * removed (currently just `eng`). Bundled packs may also appear in
 * the user data dir if they've been updated; the bundled flag tracks
 * the catalog status, not the on-disk source.
 */
bundled: boolean, };
