// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do with the source image's metadata (EXIF + ICC profile)
 * during a convert / compress op.
 *
 * * `Preserve` — copy EXIF + ICC chunks from the input to the output
 *   when both formats support them (currently JPEG↔JPEG and PNG↔PNG).
 *   For cross-format converts (e.g. JPEG → AVIF) the metadata is
 *   dropped.
 * * `RemovePersonal` — drop EXIF and other source ancillary metadata,
 *   retaining an exact ICC profile only on engine-proven paths.
 * * `StripAll` — drop all metadata regardless. Privacy default for
 *   shared photos; also gives the smallest output bytes.
 */
export type MetadataPolicy = "preserve" | "remove_personal" | "strip_all";
