// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether one metadata policy can be applied to a source/target pair and the
 * engine-owned explanation shown to clients.
 */
export type MetadataPolicyAvailability = { available: boolean, reason: string | null, summary: string, };
