// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which metadata "family" a file belongs to. Drives both engine routing
 * (which reader/writer to call) and which UI form the frontend shows.
 * Detected by file extension; `Other` is the catch-all for anything we
 * don't have a dedicated reader for.
 */
export type MetadataDomain = "audio" | "image" | "video" | "pdf" | "other";
