// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTags } from "./AudioTags";
import type { CoverArt } from "./CoverArt";
import type { MetadataDomain } from "./MetadataDomain";
import type { RawTag } from "./RawTag";

/**
 * The result of reading one file's metadata. `audio`/`cover_art` are
 * populated only for the `Audio` domain; `raw` is the universal grouped
 * key/value list and is populated for every readable domain (it also backs
 * the "all tags" expander for audio).
 */
export type MetadataView = { path: string, domain: MetadataDomain, audio: AudioTags | null, cover_art: CoverArt | null, raw: Array<RawTag>, };
