// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do with the source image's metadata (EXIF + ICC profile)
 * during a convert / compress op. Two policies in v0.2.5:
 *
 * * `Preserve` — copy EXIF + ICC chunks from the input to the output
 *   when both formats support them (currently JPEG↔JPEG and PNG↔PNG).
 *   For cross-format converts (e.g. JPEG → AVIF) the metadata is
 *   dropped — v0.2.5.1 will broaden the supported matrix.
 * * `StripAll` — drop all metadata regardless. Privacy default for
 *   shared photos; also gives the smallest output bytes.
 *
 * `StripExifKeepIcc` (drop EXIF but keep the colour profile) was on
 * the v0.2.5 plan but deferred per the explicit per-format-fragility
 * trigger; arriving in v0.2.5.1.
 */
export type MetadataPolicy = "preserve" | "strip_all";
