// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetadataWriteItem } from "./MetadataWriteItem";

/**
 * Queue payload for a metadata write. A batch "Apply" enqueues a single
 * `Write` job carrying every selected file; the worker writes each in turn
 * and emits N/total progress. Tagged like `PdfOperation`/`ImageOperation`
 * so adding future ops (e.g. image EXIF write) stays additive.
 */
export type MetadataOperation = { "kind": "write", items: Array<MetadataWriteItem>, backup: boolean, };
