// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioTags } from "./AudioTags";
import type { CoverArtOp } from "./CoverArtOp";

/**
 * One file's write request inside a batch. `audio` carries the field-level
 * changes (None=untouched); `cover_art` the picture op.
 */
export type MetadataWriteItem = { path: string, audio: AudioTags, cover_art: CoverArtOp, };
