// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What to do with the source image's metadata (EXIF + ICC profile)
 * during a convert / compress op. Two policies as of v0.2.6:
 *
 * * `Preserve` — copy EXIF + ICC chunks from the input to the output
 *   when both formats support them (currently JPEG↔JPEG and PNG↔PNG).
 *   For cross-format converts (e.g. JPEG → AVIF) the metadata is
 *   dropped. Broadening the supported matrix is a v0.2.7+ candidate.
 * * `StripAll` — drop all metadata regardless. Privacy default for
 *   shared photos; also gives the smallest output bytes.
 *
 * `StripExifKeepIcc` (drop EXIF but keep the colour profile) is a
 * v0.2.7+ candidate per the explicit per-format-fragility trigger.
 */
export type MetadataPolicy = "preserve" | "strip_all";
