// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inclusive page range for `PdfOperation::Split`. `start` and `end` are
 * 1-indexed and `end >= start`. The range parser enforces this invariant.
 */
export type PageRange = { start: number, end: number, };
