// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RotationDegrees } from "./RotationDegrees";

/**
 * Per-page rotation override. `page` is 1-indexed. Pages not listed in a
 * `PdfOperation::Rotate.rotations` vector are left untouched — so a
 * "rotate all 90°" UI affordance expands to `(1..=N).map(|p| PageRotation
 * { page: p, rotation: Cw90 })`.
 */
export type PageRotation = { page: number, rotation: RotationDegrees, };
