// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output format for `PdfOperation::ExtractImages`. mutool's `draw` subcommand
 * supports both via `-F png` / `-F jpg`.
 */
export type PdfImageFormat = "png" | "jpeg";
