// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Subset of PDF `/Info` dictionary fields exposed to the UI. `None` for a
 * field means "leave existing value untouched"; `Some("")` clears it.
 * PDF creation/modification date timestamps are managed by the writer and
 * not user-editable here.
 */
export type PdfMetadata = { title: string | null, author: string | null, subject: string | null, keywords: string | null, };
