// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageRange } from "./PageRange";
import type { PdfQuality } from "./PdfQuality";

/**
 * What to do with a PDF. Merge takes multiple inputs and produces one
 * output; Split takes one input and produces one file per `PageRange`;
 * Compress re-encodes a single input via Ghostscript at the chosen quality.
 */
export type PdfOperation = { "kind": "merge", inputs: Array<string>, output_path: string, } | { "kind": "split", input: string, ranges: Array<PageRange>, output_dir: string, } | { "kind": "compress", input: string, output_path: string, quality: PdfQuality, };
