// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageRange } from "./PageRange";
import type { PageRotation } from "./PageRotation";
import type { PdfMetadata } from "./PdfMetadata";
import type { PdfQuality } from "./PdfQuality";

/**
 * What to do with a PDF. The original three ops (Merge, Split, Compress)
 * retain their wire shape — adding variants is additive only.
 */
export type PdfOperation = { "kind": "merge", inputs: Array<string>, output_path: string, } | { "kind": "split", input: string, ranges: Array<PageRange>, output_dir: string, } | { "kind": "compress", input: string, output_path: string, quality: PdfQuality, } | { "kind": "extract_pages", input: string, ranges: Array<PageRange>, output_path: string, } | { "kind": "rotate", input: string, rotations: Array<PageRotation>, output_path: string, } | { "kind": "reorder", input: string, order: Array<number>, output_path: string, } | { "kind": "delete_pages", input: string, pages: Array<number>, output_path: string, } | { "kind": "insert_blank", input: string, positions: Array<number>, output_path: string, } | { "kind": "set_metadata", input: string, metadata: PdfMetadata, output_path: string, };
