// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `pdf_probe` — used by the UI before it picks an operation so
 * range inputs know the page count bounds.
 */
export type PdfProbeResult = { pages: number, bytes: bigint, };
