// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ghostscript preset for PDF compression. Maps to `-dPDFSETTINGS=/<name>`:
 * Screen = smallest/lowest quality (~72 dpi images), Ebook = medium
 * (~150 dpi), Printer = highest (~300 dpi).
 */
export type PdfQuality = "screen" | "ebook" | "printer";
