// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressMode } from "./CompressMode";
import type { QualityPreset } from "./QualityPreset";
import type { ResolutionCap } from "./ResolutionCap";
import type { TargetFormat } from "./TargetFormat";

/**
 * A saved combination of target format + quality / resolution / compression
 * settings, named by the user. Applied from the Convert or Compress page.
 *
 * A single preset can carry Convert fields (`quality_preset`,
 * `resolution_cap`) and Compress fields (`compress_mode`). Each page applies
 * only the fields relevant to it. Presets without a `compress_mode` are
 * hidden from the Compress page's chip picker.
 */
export type Preset = { id: string, name: string, target: TargetFormat, quality_preset: QualityPreset | null, resolution_cap: ResolutionCap | null, compress_mode: CompressMode | null, is_builtin: boolean, created_at: bigint, };
