// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewKind } from "./PreviewKind";

export type PreviewResult = { request_id: string, source_revision: string, kind: PreviewKind, before_path: string | null, after_path: string, width: number, height: number, sample_bytes: number, duration_ms: number | null, max_edge: number, max_duration_ms: number, };
