// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompressMode } from "./CompressMode";
import type { GifOptions } from "./GifOptions";
import type { ImageAlphaPolicy } from "./ImageAlphaPolicy";
import type { ImageColorPolicy } from "./ImageColorPolicy";
import type { ImageConvertOptions } from "./ImageConvertOptions";
import type { MetadataPolicy } from "./MetadataPolicy";
import type { QualityPreset } from "./QualityPreset";
import type { ResolutionCap } from "./ResolutionCap";
import type { SubtitleOptions } from "./SubtitleOptions";
import type { TargetFormat } from "./TargetFormat";
import type { VideoConvertOptions } from "./VideoConvertOptions";

export type PreviewRequest = { video_options?: VideoConvertOptions | null, request_id: string, input_path: string, source_revision: string, target: TargetFormat, quality_preset: QualityPreset | null, resolution_cap: ResolutionCap | null, compress_mode: CompressMode | null, metadata_policy: MetadataPolicy | null, image_color_policy?: ImageColorPolicy | null, image_alpha_policy?: ImageAlphaPolicy | null, subtitle: SubtitleOptions | null, gif_options: GifOptions | null, image_options?: ImageConvertOptions | null, };
