// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Engine-owned admission result for the current bounded preview request.
 *
 * `available` means the request passed deterministic preflight. Generation
 * still revalidates the source and can fail during bounded decode or encode.
 */
export type PreviewEligibility = { available: boolean, reason: string | null, };
