// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProbeResult = { duration_ms: bigint, width: number | null, height: number | null, video_codec: string | null, audio_codec: string | null, file_size: bigint, container: string | null, has_video: boolean, has_audio: boolean, };
