// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

export type ProbeResult = { duration_ms: bigint, width: number | null, height: number | null, video_codec: string | null, audio_codec: string | null, file_size: bigint, container: string | null, has_video: boolean, has_audio: boolean, source_kind: SourceKind, color_space: string | null, image_format: string | null, 
/**
 * True when the source carries at least one subtitle stream —
 * either a bare `.srt` / `.vtt` or a container with embedded subs.
 */
has_subtitles: boolean, 
/**
 * Codecs of every subtitle stream, in stream order (`subrip`,
 * `webvtt`, `hdmv_pgs_subtitle`, …). The full list matters because
 * text and bitmap subtitles can't be transcoded into each other, so
 * preserving existing tracks is only safe when they are all text.
 */
subtitle_codecs: Array<string>, };
