// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";

export type ProgressEvent = { job_id: JobId, percent: number, eta_secs: bigint | null, speed_hr: string | null, stage: string, 
/**
 * Name of the active encoder, when known. Set for ffmpeg jobs that go
 * through a hardware encoder (e.g. `h264_videotoolbox`) so the UI can
 * show a "HW" badge. `None` for software encodes, remuxes, downloads,
 * and PDF jobs.
 */
encoder: string | null, };
