// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";

export type ProgressEvent = { job_id: JobId, percent: number, eta_secs: bigint | null, speed_hr: string | null, stage: string, };
