// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobId } from "./JobId";
import type { JobResult } from "./JobResult";
import type { JobState } from "./JobState";

export type QueueEvent = { job_id: JobId, state: JobState, result: JobResult | null, };
