// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single raw tag as surfaced in the universal read-only viewer. `group`
 * buckets related tags (e.g. `EXIF`, `GPS`, `Format`, `Stream:0`, `Audio`,
 * `PDF`); `tag` is the human-readable field name; `value` is the rendered
 * string. The frontend groups by `group` for display.
 */
export type RawTag = { group: string, tag: string, value: string, };
