// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a `Resize` operation handles the target box.
 * * `FitWithin` preserves aspect ratio and fits within (width, height) —
 *   the result may be smaller than the target in one dimension.
 * * `FitExact` resizes to exactly (width, height), potentially
 *   distorting aspect ratio.
 * * `Scale` interprets `width` as a percentage (e.g. 50 = 50%) and
 *   ignores `height`.
 */
export type ResizeMode = "fit_within" | "fit_exact" | "scale";
