// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminator for `JobResult.output_path` shape.
 *
 * `File` — `output_path` points at a single file (yt-dlp default,
 * most converter/PDF jobs). The frontend's "Reveal" action selects
 * the file in Finder/Explorer.
 *
 * `Folder` — `output_path` points at a directory containing N files
 * (gallery-dl albums, multi-file PDF splits). The frontend's
 * "Open folder" action opens the containing directory; the queue row
 * shows file-count progress instead of byte-percent.
 */
export type ResultKind = "file" | "folder";
