// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clockwise rotation applied to a PDF page. The PDF spec stores `/Rotate`
 * in 90-degree increments; only these three are useful (0 is no-op).
 * The backend composes the new rotation with any existing `/Rotate` value
 * modulo 360, so a single rotation that lands a page back at 0 is fine.
 */
export type RotationDegrees = "cw90" | "cw180" | "cw270";
