// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Clockwise rotation in 90-degree increments. Shared between PDF page
 * rotation (`PdfOperation::Rotate`) and single-image rotation
 * (`ImageOperation::Rotate`). 0 is the no-op identity and is intentionally
 * excluded so callers must pick a real rotation. For PDF pages, the
 * backend composes this with any existing `/Rotate` value modulo 360, so
 * a rotation that lands a page back at 0 is fine.
 */
export type RotationDegrees = "cw90" | "cw180" | "cw270";
