// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryViewMode } from "./HistoryViewMode";
import type { Theme } from "./Theme";

export type SettingsPatch = { output_dir: string | null, theme: Theme | null, yt_dlp_last_update_ms: bigint | null, extract_concurrency: number | null, convert_concurrency: number | null, auto_check_updates: boolean | null, dismissed_update_version: string | null, history_view_mode: HistoryViewMode | null, queue_sidebar_width: number | null, hw_acceleration_enabled: boolean | null, 
/**
 * Tri-state on the wire:
 * - field absent → no change
 * - `Some(Some("chrome"))` → set to a specific browser
 * - `Some(None)` → clear (turn cookies off)
 */
cookies_from_browser: string | null | null, 
/**
 * Phase I (v0.2.0): set to `Some(true)` when the user finishes or
 * skips onboarding; `Some(false)` from Settings → About to
 * re-show the welcome screen.
 */
has_seen_onboarding: boolean | null, };
