// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type SettingsPatch = { output_dir: string | null, theme: Theme | null, yt_dlp_last_update_ms: bigint | null, extract_concurrency: number | null, convert_concurrency: number | null, };
