// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryViewMode } from "./HistoryViewMode";
import type { Theme } from "./Theme";

export type Settings = { output_dir: string, theme: Theme, yt_dlp_last_update_ms: bigint | null, extract_concurrency: number, convert_concurrency: number, auto_check_updates: boolean, dismissed_update_version: string | null, history_view_mode: HistoryViewMode, };
