// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractNamingScheme } from "./ExtractNamingScheme";
import type { HistoryViewMode } from "./HistoryViewMode";
import type { MetadataPolicy } from "./MetadataPolicy";
import type { Theme } from "./Theme";

export type SettingsPatch = { output_dir: string | null, theme: Theme | null, yt_dlp_last_update_ms: bigint | null, extract_concurrency: number | null, convert_concurrency: number | null, auto_check_updates: boolean | null, dismissed_update_version: string | null, history_view_mode: HistoryViewMode | null, queue_sidebar_width: number | null, hw_acceleration_enabled: boolean | null, 
/**
 * Tri-state on the wire (see `double_option` helper above):
 * - field absent → `None` (no change)
 * - `null`       → `Some(None)` (clear)
 * - `"chrome"`   → `Some(Some("chrome"))` (set)
 */
cookies_from_browser: string | null | null, 
/**
 * Phase I (v0.2.0): set to `Some(true)` when the user finishes or
 * skips onboarding; `Some(false)` from Settings → About to
 * re-show the welcome screen.
 */
has_seen_onboarding: boolean | null, notifications_enabled: boolean | null, 
/**
 * Tri-state on the wire (see `double_option` helper):
 * - field absent → `None` (no change)
 * - `null`       → `Some(None)` (clear the override)
 * - `"/path"`    → `Some(Some(path))` (set)
 */
output_dir_extract: string | null | null, extract_naming_scheme: ExtractNamingScheme | null, default_metadata_policy: MetadataPolicy | null, 
/**
 * Tri-state on the wire (see `double_option` helper):
 * - field absent → `None` (no change)
 * - `null`       → `Some(None)` (clear)
 * - `"tb-…"`     → `Some(Some(key))` (set)
 */
torbox_api_key: string | null | null, };
