// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type Settings = { output_dir: string, theme: Theme, yt_dlp_last_update_ms: bigint | null, extract_concurrency: number, convert_concurrency: number, };
