// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryViewMode } from "./HistoryViewMode";
import type { Theme } from "./Theme";

export type Settings = { output_dir: string, theme: Theme, yt_dlp_last_update_ms: bigint | null, extract_concurrency: number, convert_concurrency: number, auto_check_updates: boolean, dismissed_update_version: string | null, history_view_mode: HistoryViewMode, queue_sidebar_width: number, hw_acceleration_enabled: boolean, 
/**
 * When set, every yt-dlp spawn (probe + download) is invoked with
 * `--cookies-from-browser <name>`. Lets users download videos from
 * sites that require login (Twitter, Instagram, etc.) by reusing
 * their existing browser session. `None` = no cookies passed.
 */
cookies_from_browser: string | null, 
/**
 * Phase I (v0.2.0): tracks whether the user has dismissed the
 * first-run onboarding flow. Defaults to false; flipped to true
 * when the user finishes or skips. Re-accessible from
 * Settings → About via a "Show welcome screen" button that
 * flips it back to false.
 */
has_seen_onboarding: boolean, };
