// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SidecarStatus = { ffmpeg_path: string | null, yt_dlp_path: string | null, yt_dlp_version: string | null, gallery_dl_path: string | null, gallery_dl_version: string | null, };
