// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WarningCode } from "./WarningCode";

export type SidecarEvent = { "kind": "yt_dlp_updated", from_version: string, to_version: string, } | { "kind": "warning", code: WarningCode, message: string, };
