// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Source = "you_tube" | "sound_cloud" | "tik_tok" | "instagram" | "twitter" | "vimeo" | "reddit" | "generic";
