// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opaque color expressed in the destination sRGB encoding.
 */
export type SrgbColor = { red: number, green: number, blue: number, };
