// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtitleMode } from "./SubtitleMode";

/**
 * An external `.srt` / `.vtt` to attach during a video conversion.
 *
 * `None` on a `ConvertRequest` means no subtitle handling at all — the
 * pre-subtitle behaviour.
 */
export type SubtitleOptions = { source_path: string, mode: SubtitleMode, };
