// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How an external subtitle file is attached to a video conversion.
 */
export type SubtitleMode = "soft" | "burn_in";
