// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TargetFormat } from "./TargetFormat";

export type TargetCapability = { target: TargetFormat, available: boolean, reason: string | null, preserves_metadata: boolean, metadata_warning: string | null, };
