// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioSettingsCapabilities } from "./AudioSettingsCapabilities";
import type { CompressionCapabilities } from "./CompressionCapabilities";
import type { ImageSettingsCapabilities } from "./ImageSettingsCapabilities";
import type { TargetFormat } from "./TargetFormat";
import type { VideoSettingsCapabilities } from "./VideoSettingsCapabilities";

export type TargetCapability = { audio_settings?: AudioSettingsCapabilities | null, video_settings?: VideoSettingsCapabilities | null, compression?: CompressionCapabilities | null, image_settings?: ImageSettingsCapabilities | null, target: TargetFormat, available: boolean, reason: string | null, preserves_metadata: boolean, metadata_warning: string | null, };
