// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioSettingsCapabilities } from "./AudioSettingsCapabilities";
import type { CompressionCapabilities } from "./CompressionCapabilities";
import type { ImageMetadataCapabilities } from "./ImageMetadataCapabilities";
import type { ImageSettingsCapabilities } from "./ImageSettingsCapabilities";
import type { TargetFormat } from "./TargetFormat";
import type { TrackSettingsCapabilities } from "./TrackSettingsCapabilities";
import type { VideoSettingsCapabilities } from "./VideoSettingsCapabilities";
import type { VideoTrackSettingsCapabilities } from "./VideoTrackSettingsCapabilities";

/**
 * Availability for one target, including optional source-bound track settings.
 * Track settings remain absent for legacy or Automatic-only inspection.
 */
export type TargetCapability = { audio_settings?: AudioSettingsCapabilities | null, video_settings?: VideoSettingsCapabilities | null, track_settings?: TrackSettingsCapabilities | null, video_track_settings?: VideoTrackSettingsCapabilities | null, compression?: CompressionCapabilities | null, image_settings?: ImageSettingsCapabilities | null, image_metadata?: ImageMetadataCapabilities | null, target: TargetFormat, available: boolean, reason: string | null, preserves_metadata: boolean, metadata_warning: string | null, };
