// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetFormat = "mp4" | "mkv" | "webm" | "gif" | "avi" | "mov" | "mp3" | "m4a" | "opus" | "wav" | "flac" | "ogg" | "aac" | "extract_audio_keep_codec" | "png" | "jpeg" | "webp" | "bmp";
