// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TargetFormat = "mp4" | "mkv" | "webm" | "mp3" | "m4a" | "opus" | "wav" | "extract_audio_keep_codec";
