// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackPresetSelection } from "./TrackPresetSelection";

/**
 * Portable preset policy for explicit per-file track selection.
 */
export type TrackPresetPolicy = { "kind": "audio", selection: TrackPresetSelection, };
