// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Portable preset intent that deliberately omits any source-specific identity.
 */
export type TrackPresetSelection = { "kind": "choose_per_file" };
