// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackSourceBinding } from "./TrackSourceBinding";

/**
 * Source-bound track selection attached to a conversion request.
 */
export type TrackConvertOptions = { "kind": "audio", source: TrackSourceBinding, stream_index: number, };
