// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackInventory } from "./TrackInventory";

export type TrackSourceBinding = { version: number, canonical_path: string, size_bytes: string, modified_unix_ns: string, inventory: TrackInventory, };
