// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stream disposition facts captured as part of source identity.
 */
export type TrackDispositionFacts = { default: boolean | null, forced: boolean | null, attached_pic: boolean | null, other: { [key in string]?: boolean }, malformed: boolean, };
