// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioModeAvailability } from "./AudioModeAvailability";
import type { TrackIdentity } from "./TrackIdentity";

/**
 * Copy and encode availability for one source-bound audio track.
 */
export type TrackChoiceCapability = { track: TrackIdentity, copy: AudioModeAvailability, encode: AudioModeAvailability, };
