// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackTextFact = { "kind": "missing" } | { "kind": "value", value: string, } | { "kind": "malformed" };
