// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One explicit retain/drop policy for a family of embedded video streams.
 * `Choose` is source-bound and always lists absolute stream indices in source
 * order. An empty selection is represented only by `None`.
 */
export type TrackStreamPolicy = { "kind": "keep_all" } | { "kind": "choose", stream_indices: Array<number>, } | { "kind": "none" };
