// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackInventory } from "./TrackInventory";

/**
 * Source facts to which an explicit track choice is bound.
 *
 * `size_bytes` and `modified_unix_ns` are canonical unsigned decimal strings
 * so JSON and JavaScript round trips cannot lose 64-bit integer precision.
 */
export type TrackSourceBinding = { version: number, canonical_path: string, size_bytes: string, modified_unix_ns: string, inventory: TrackInventory, };
