// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Portable video-preset intent for one stream family. Exact source indices
 * never enter a preset: source-specific `Choose` becomes `ChoosePerFile`.
 */
export type TrackPresetStreamPolicy = { "kind": "keep_all" } | { "kind": "choose_per_file" } | { "kind": "none" };
