// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackIdentity } from "./TrackIdentity";

/**
 * Complete, absolute-index-ordered stream identity for one source inspection.
 */
export type TrackInventory = { version: number, streams: Array<TrackIdentity>, };
