// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A bounded text fact that preserves the difference between absent, valid,
 * and malformed probe metadata.
 */
export type TrackTextFact = { "kind": "missing" } | { "kind": "value", value: string, } | { "kind": "malformed" };
