// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One source-bound track or policy availability result for explicit video.
 */
export type TrackModeAvailability = { available: boolean, reason: string | null, };
