// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackChoiceCapability } from "./TrackChoiceCapability";
import type { TrackSourceBinding } from "./TrackSourceBinding";

export type TrackSettingsCapabilities = { source: TrackSourceBinding, audio_choices: Array<TrackChoiceCapability>, };
