// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress tick emitted to the UI while a download is in flight.
 */
export type UpdateProgress = { downloaded: bigint, total: bigint, };
