// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Describes a newer release of Goop available on GitHub. Produced by the
 * `check_for_update` IPC command when the latest GitHub release is strictly
 * newer than the running app's version. `download_url` points at the asset
 * matching the current platform (macOS aarch64/x64 `.dmg`, Windows `.msi`
 * or `.exe`).
 */
export type UpdateInfo = { current_version: string, latest_version: string, download_url: string, asset_size: bigint, release_notes: string, published_at: string, };
