// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateStatus = { attempted: boolean, previous_version: string | null, new_version: string | null, message: string, };
