// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FormatOption } from "./FormatOption";

export type UrlProbe = { url: string, title: string, uploader: string | null, duration_secs: bigint | null, thumbnail_url: string | null, formats: Array<FormatOption>, };
