// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebridProbeInfo } from "./DebridProbeInfo";
import type { DirectFileInfo } from "./DirectFileInfo";
import type { ExtractorChoice } from "./ExtractorChoice";
import type { FormatOption } from "./FormatOption";

export type UrlProbe = { url: string, title: string, uploader: string | null, duration_secs: bigint | null, thumbnail_url: string | null, formats: Array<FormatOption>, 
/**
 * Set only when neither extractor recognised the URL and a direct
 * HTTP `HEAD`/`GET` probe found a plain downloadable file. The UI
 * renders a simplified "Direct download" card in this case. `None`
 * for normal yt-dlp / gallery-dl results.
 */
direct: DirectFileInfo | null, 
/**
 * Set when the URL routes through the debrid service: always for
 * `magnet:` links, and for hoster links the probe matched against
 * TorBox's supported-hoster list. The UI renders a "via TorBox"
 * card. `None` everywhere else.
 */
debrid: DebridProbeInfo | null, 
/**
 * Which extractor produced this probe. Echoed back by the UI as
 * `ExtractRequest::extractor_hint` so the download skips the guess —
 * same round trip as `direct` and `debrid`. `None` for direct and
 * debrid probes, where no extractor was involved.
 */
extractor: ExtractorChoice | null, };
