// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectFileInfo } from "./DirectFileInfo";
import type { FormatOption } from "./FormatOption";

export type UrlProbe = { url: string, title: string, uploader: string | null, duration_secs: bigint | null, thumbnail_url: string | null, formats: Array<FormatOption>, 
/**
 * Set only when neither extractor recognised the URL and a direct
 * HTTP `HEAD`/`GET` probe found a plain downloadable file. The UI
 * renders a simplified "Direct download" card in this case. `None`
 * for normal yt-dlp / gallery-dl results.
 */
direct: DirectFileInfo | null, };
