// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit presentation-timing policy for Custom video encoding.
 */
export type VideoFrameRate = { "kind": "preserve" } | { "kind": "constant", numerator: number, denominator: number, };
