// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackConvertOptions } from "./TrackConvertOptions";
import type { TrackIdentity } from "./TrackIdentity";
import type { VideoTrackStreamOutcome } from "./VideoTrackStreamOutcome";

/**
 * Authoritative multi-stream disclosure for an explicit 05B video request.
 */
export type VideoTrackExecutionSummary = { requested: TrackConvertOptions, retained: Array<VideoTrackStreamOutcome>, omitted_audio: Array<TrackIdentity>, omitted_subtitles: Array<TrackIdentity>, notices: Array<string>, };
