// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit encoding processor policy, persisted independently of global preferences.
 */
export type VideoProcessor = "software";
