// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoCodec } from "./VideoCodec";
import type { VideoConvertOptions } from "./VideoConvertOptions";

export type VideoExecutionSummary = { requested: VideoConvertOptions, 
/**
 * The resolved software encoder; absent when video is copied.
 */
encoder?: string | null, video_codec: VideoCodec, video_stream_index: number, audio_stream_index?: number | null, audio_codec?: string | null, audio_copied: boolean, width: number, height: number, notices: Array<string>, };
