// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoRationalFact } from "./VideoRationalFact";

/**
 * Source stream facts; missing optional values represent unknown probe facts.
 */
export type VideoStreamInfo = { 
/**
 * Absolute source stream index reported by the probe, not a video-only ordinal.
 */
index: number, codec_type: string, codec_name?: string | null, pixel_format?: string | null, color_transfer?: string | null, color_primaries?: string | null, color_space?: string | null, color_range?: string | null, field_order?: string | null, sample_aspect_ratio?: string | null, rotation_degrees?: number | null, 
/**
 * Malformed, non-integral or conflicting rotation/display information.
 * A missing rotation value alone does not imply ambiguity.
 */
rotation_ambiguous: boolean, attached_pic: boolean, average_frame_rate?: VideoRationalFact | null, base_frame_rate?: VideoRationalFact | null, time_base?: VideoRationalFact | null, start_time_ms?: number, duration_ms?: number, };
