// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The first portable explicit hardware codec contract. Encoder names remain
 * execution facts and are not persisted as user intent.
 */
export type VideoHardwareCodec = "h264";
