// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoCodec } from "./VideoCodec";
import type { VideoProcessor } from "./VideoProcessor";
import type { VideoRateControl } from "./VideoRateControl";
import type { VideoSpeed } from "./VideoSpeed";

export type VideoConvertOptions = { "kind": "copy" } | { "kind": "encode", codec: VideoCodec, rate_control: VideoRateControl, speed: VideoSpeed, processor: VideoProcessor, };
