// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VideoRateControl = { "kind": "constant_quality", crf: number, } | { "kind": "average_bitrate", kbps: number, };
