// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackIdentity } from "./TrackIdentity";
import type { TrackModeAvailability } from "./TrackModeAvailability";

/**
 * Copy and Custom availability for one audio or embedded subtitle stream.
 */
export type VideoTrackChoiceCapability = { track: TrackIdentity, copy: TrackModeAvailability, custom: TrackModeAvailability, };
