// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackModeAvailability } from "./TrackModeAvailability";

/**
 * Availability of the three policies within one video processing mode.
 */
export type VideoTrackPolicyModeCapabilities = { keep_all: TrackModeAvailability, choose: TrackModeAvailability, none: TrackModeAvailability, };
