// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Completed processing for one retained audio or subtitle stream in a 05B
 * video conversion. Audio fallback is fixed to AAC at 192 kbps.
 */
export type VideoTrackProcessing = { "kind": "copied" } | { "kind": "encoded_aac", bitrate_kbps: number, };
