// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackIdentity } from "./TrackIdentity";
import type { TrackTextFact } from "./TrackTextFact";
import type { VideoTrackProcessing } from "./VideoTrackProcessing";

/**
 * Verified source-to-output facts for one retained auxiliary stream.
 */
export type VideoTrackStreamOutcome = { source: TrackIdentity, output_stream_index: number, output_type_index: number, processing: VideoTrackProcessing, source_codec_tag: TrackTextFact, output_codec_name: TrackTextFact, output_codec_tag: TrackTextFact, output_language: TrackTextFact, output_title: TrackTextFact, output_default: boolean | null, output_forced: boolean | null, };
