// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoStreamInfo } from "./VideoStreamInfo";

export type VideoProbeDetails = { streams: Array<VideoStreamInfo>, };
