// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Encoder names admitted by the current video planners, not proof of device utilization.
 */
export type VideoEncoder = "libx264" | "libx265" | "libvpx-vp9" | "mpeg4" | "h264_videotoolbox" | "h264_nvenc" | "h264_qsv" | "h264_amf";
