// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One video rate-control mode. CRF admits 1..=51 (lower is higher quality);
 * average bitrate admits 100..=200000 kbps and is not an exact output-size promise.
 * Deserialization checks shape and integer types; callers must validate bounds.
 */
export type VideoRateControl = { "kind": "constant_quality", crf: number, } | { "kind": "average_bitrate", kbps: number, };
