// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoCodec } from "./VideoCodec";

export type VideoCodecCapability = { codec: VideoCodec, encoder: string, available: boolean, reason?: string | null, recommended_crf: number, };
