// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoFrameRate } from "./VideoFrameRate";
import type { VideoFrameRateChoice } from "./VideoFrameRateChoice";
import type { VideoRationalFact } from "./VideoRationalFact";

/**
 * Engine-owned source timing facts and supported Custom timing choices.
 */
export type VideoFrameRateCapabilities = { available: boolean, reason?: string | null, default?: VideoFrameRate | null, constant_choices: Array<VideoFrameRateChoice>, average_frame_rate?: VideoRationalFact | null, base_frame_rate?: VideoRationalFact | null, time_base?: VideoRationalFact | null, };
