// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Software encoder preset names; speed is independent of rate control and audio.
 */
export type VideoSpeed = "fast" | "medium" | "slow";
