// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoFrameRateCapabilities } from "./VideoFrameRateCapabilities";
import type { VideoHardwareCodec } from "./VideoHardwareCodec";
import type { VideoResizeCapabilities } from "./VideoResizeCapabilities";

/**
 * Engine-owned eligibility for the explicit Hardware required mode. This is
 * compiled encoder and option-contract evidence, not proof of a usable device
 * session; runtime failure remains possible and never enables substitution.
 */
export type VideoHardwareCapabilities = { available: boolean, reason?: string | null, codec: VideoHardwareCodec, bitrate_min_kbps: number, bitrate_max_kbps: number, default_bitrate_kbps: number, resize?: VideoResizeCapabilities | null, frame_rate?: VideoFrameRateCapabilities | null, };
