// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Video codecs admitted by explicit Copy and software Encode modes.
 */
export type VideoCodec = "h264" | "hevc";
