// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoFrameRate } from "./VideoFrameRate";

/**
 * One named exact constant frame-rate choice.
 */
export type VideoFrameRateChoice = { frame_rate: VideoFrameRate, label: string, };
