// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoStreamInfo } from "./VideoStreamInfo";

/**
 * Complete source stream inventory used for explicit video admission.
 * Stored details do not replace a fresh execution-time probe.
 */
export type VideoProbeDetails = { streams: Array<VideoStreamInfo>, };
