// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoEncoder } from "./VideoEncoder";
import type { VideoFallback } from "./VideoFallback";
import type { VideoSelectionContext } from "./VideoSelectionContext";

/**
 * Facts about completed processing, frozen before publication. Ordinal is internal
 * to this conversion, not the queue attempt count. Absent receipts remain unknown.
 */
export type VideoAttempt = { "kind": "copy" } | { "kind": "encode", encoder: VideoEncoder, encode_attempt_ordinal: number, selection_context: VideoSelectionContext, fallback?: VideoFallback | null, };
