// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoEncoder } from "./VideoEncoder";
import type { VideoFallbackReason } from "./VideoFallbackReason";

export type VideoFallback = { from_encoder: VideoEncoder, reason: VideoFallbackReason, };
