// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Explicit output geometry for Custom video encoding.
 */
export type VideoResize = { "kind": "original" } | { "kind": "fit_within", width: number, height: number, };
