// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution-time legacy preference is distinct from explicit per-job Software intent.
 */
export type VideoSelectionContext = { "kind": "explicit_software" } | { "kind": "legacy_global_at_execution", hw_acceleration_enabled: boolean, };
