// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rate control admitted by explicit hardware-required encoding.
 */
export type VideoHardwareRateControl = { "kind": "average_bitrate", kbps: number, };
