// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoTrackPolicyModeCapabilities } from "./VideoTrackPolicyModeCapabilities";

/**
 * Copy and Custom policy-level availability for one stream family.
 */
export type VideoTrackPolicyCapabilities = { copy: VideoTrackPolicyModeCapabilities, custom: VideoTrackPolicyModeCapabilities, };
