// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoResize } from "./VideoResize";

/**
 * Engine-owned bounds and default for Custom video dimensions.
 */
export type VideoResizeCapabilities = { available: boolean, reason?: string | null, min_dimension: number, max_dimension: number, no_enlargement: boolean, default: VideoResize, };
