// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One observed exact rational or a probe value that was present but unusable.
 * Absence on the containing field means the probe value was missing.
 */
export type VideoRationalFact = { "kind": "exact", numerator: number, denominator: number, } | { "kind": "malformed" };
