// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hardware-required means the admitted hardware encoder must be used and no
 * software substitution or retry is permitted.
 */
export type VideoHardwarePolicy = { "kind": "required" };
