// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VideoCodec } from "./VideoCodec";

/**
 * Availability of one concrete software encoder for this source and target.
 */
export type VideoCodecCapability = { codec: VideoCodec, encoder: string, available: boolean, reason?: string | null, 
/**
 * Codec-specific recommendation; does not imply equal quality across codecs.
 */
recommended_crf: number, };
