// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackSourceBinding } from "./TrackSourceBinding";
import type { VideoTrackChoiceCapability } from "./VideoTrackChoiceCapability";
import type { VideoTrackPolicyCapabilities } from "./VideoTrackPolicyCapabilities";

/**
 * Source binding, per-stream reasons and policy-level availability for 05B.
 */
export type VideoTrackSettingsCapabilities = { source: TrackSourceBinding, audio_tracks: Array<VideoTrackChoiceCapability>, subtitle_tracks: Array<VideoTrackChoiceCapability>, audio_policy: VideoTrackPolicyCapabilities, subtitle_policy: VideoTrackPolicyCapabilities, };
