// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Engine-derived availability of a processing mode and its unavailable reason.
 */
export type VideoModeAvailability = { available: boolean, reason?: string | null, };
