// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable discriminant for `SidecarEvent::Warning`.
 *
 * This is not a display string — the frontend routes on it. `handleSidecarEvent`
 * in `src/store/appStore.ts` switches on the code to pick a side effect, and a
 * code it doesn't recognize is dropped rather than shown as a generic warning.
 * Keeping this an enum rather than a `String` is what makes a rename or typo a
 * compile error on both sides instead of a silent no-op.
 *
 * Adding a variant requires a matching branch in `handleSidecarEvent`; its
 * exhaustiveness check fails the frontend typecheck until one exists.
 * Regenerate the TS bindings (`scripts/generate-bindings.sh`) after any change
 * here.
 */
export type WarningCode = "cookie_fallback" | "subtitle_cues_dropped";
