// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Anchor for a `Watermark` overlay relative to the image bounds.
 */
export type WatermarkPosition = "top_left" | "top_right" | "bottom_left" | "bottom_right" | "center";
