// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WatermarkPosition } from "./WatermarkPosition";

/**
 * Text watermark specification. v0.2.5 ships text-only watermarks; image
 * overlay variants are deferred to v0.2.6. `opacity` is 0..=100 percent;
 * the backend clamps.
 */
export type WatermarkSpec = { text: string, position: WatermarkPosition, opacity: number, };
