#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# Use TS_RS_EXPORT_DIR to force consolidation at workspace root regardless of
# each `#[ts(export_to = "...")]` attribute. ts-rs joins this base dir with the
# per-type output_path, and the `../../shared/types/` attributes resolve back to
# this same directory.
export TS_RS_EXPORT_DIR="$(pwd)/shared/types"

rm -rf shared/types
mkdir -p shared/types

# Running each crate's tests triggers ts-rs export (the `#[ts(export)]` attr
# writes files via auto-generated tests).
cargo test -p goop-core -p goop-extractor -p goop-queue -p goop-config -p goop-sidecar --all-features --no-fail-fast -- --nocapture
cargo test -p goop-tauri --all-features --no-fail-fast -- --nocapture

# Concatenate all generated .ts files into a single index.ts.
# macOS find is BSD: use `! -name` instead of `-not -name`.
{
  echo "// Generated by ts-rs. Do not edit."
  find shared/types -name '*.ts' ! -name 'index.ts' -type f | sort | while read -r f; do
    rel="${f#shared/types/}"
    no_ext="${rel%.ts}"
    echo "export * from './${no_ext}';"
  done
} > shared/types/index.ts

count="$(find shared/types -name '*.ts' ! -name 'index.ts' -type f | wc -l | tr -d ' ')"
echo "Bindings generated. ${count} types exported."
