#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# ts-rs writes each type through an auto-generated test. TS_RS_EXPORT_DIR is the
# base dir those tests export into; every `#[ts(export_to = "../../shared/types/")]`
# attribute is resolved relative to it, climbing two levels up and back down into
# `shared/types`. We aim that base at a throwaway staging tree and only swap the
# result over the committed bindings once every step has succeeded. The previous
# version deleted shared/types up front and depended on the cargo steps not
# failing; a failure in between (e.g. missing sidecars) left the working tree with
# a subset of bindings deleted and no index.ts, and no message saying so.

# --- Preflight: goop-tauri's build needs the sidecar binaries -----------------
# tauri_build::build() validates every externalBin entry exists for the host
# target, so without them `cargo test -p goop-tauri` fails with
# "resource path bin/<name>-<triple> doesn't exist". Check them all up front and
# fail with the fix instead of burying it under a wall of build output.
target="$(rustc -vV | awk '/host/ { print $2 }')"
if [[ -z "$target" ]]; then
  echo "generate-bindings: could not determine the host target from 'rustc -vV'." >&2
  exit 1
fi
# Keep this list in sync with externalBin in src-tauri/tauri.conf.json.
missing=()
for bin in ffmpeg ffprobe yt-dlp gallery-dl gs mutool tesseract; do
  if [[ ! -e "src-tauri/bin/${bin}-${target}" && ! -e "src-tauri/bin/${bin}-${target}.exe" ]]; then
    missing+=("${bin}-${target}")
  fi
done
if (( ${#missing[@]} > 0 )); then
  echo "generate-bindings: sidecar binaries missing from src-tauri/bin/:" >&2
  printf '  %s\n' "${missing[@]}" >&2
  echo "  goop-tauri's build needs them before its bindings can be generated. Run:" >&2
  echo "    scripts/fetch-sidecars.sh ${target}" >&2
  echo "  (in a git worktree, symlink the main checkout's src-tauri/bin instead of refetching.)" >&2
  exit 1
fi

# --- Generate into a staging tree, swap in only on success --------------------
# Staged inside the repo so the swap-in below is a same-filesystem rename(2).
stage="$(mktemp -d "$PWD/.bindings-stage.XXXXXX")"
trap 'rm -rf "$stage"' EXIT
trap 'echo "generate-bindings: FAILED before completion — existing shared/types left untouched." >&2' ERR

export TS_RS_EXPORT_DIR="$stage/shared/types"
mkdir -p "$TS_RS_EXPORT_DIR"

# Running each crate's tests triggers ts-rs export (the `#[ts(export)]` attr
# writes files via auto-generated tests).
cargo test -p goop-core -p goop-extractor -p goop-queue -p goop-config -p goop-sidecar --all-features --no-fail-fast -- --nocapture
cargo test -p goop-tauri --all-features --no-fail-fast -- --nocapture

# Concatenate all generated .ts files into a single index.ts.
# macOS find is BSD: use `! -name` instead of `-not -name`.
{
  echo "// Generated by ts-rs. Do not edit."
  find "$TS_RS_EXPORT_DIR" -name '*.ts' ! -name 'index.ts' -type f | sort | while read -r f; do
    rel="${f#"$TS_RS_EXPORT_DIR"/}"
    no_ext="${rel%.ts}"
    echo "export * from './${no_ext}';"
  done
} > "$TS_RS_EXPORT_DIR/index.ts"

# Generation succeeded. Past this point shared/types is modified, so the generic
# "left untouched" ERR message no longer applies — clear it and handle the swap
# explicitly. The swap moves the old bindings aside, moves the new set into
# place, then drops the old. Each step is a same-filesystem rename(2), so
# shared/types is never in a missing or half-written state (unlike rm-then-mv,
# which leaves a gap and silently nests if the target still exists); if the
# move-in ever fails, the previous bindings are restored so the tree is left
# exactly as found.
trap - ERR
backup=""
if [[ -e shared/types ]]; then
  backup="$stage/previous-types"
  # Guarded rather than left to `set -e`: the ERR trap is gone by now, so a
  # bare failure here would exit with nothing but mv's own stderr, despite
  # this being the one step where nothing has moved yet.
  if ! mv shared/types "$backup"; then
    echo "generate-bindings: FAILED to move the existing bindings aside." >&2
    echo "  shared/types is untouched." >&2
    exit 1
  fi
fi
if ! mv "$TS_RS_EXPORT_DIR" shared/types; then
  # Report what actually happened rather than announcing the restore before
  # trying it. Whatever stopped the move-in — permissions, quota, a remount —
  # is just as able to stop the restore a moment later on the same
  # filesystem, and claiming success there would be the exact silent loss
  # this script exists to prevent.
  if [[ -z "$backup" ]]; then
    echo "generate-bindings: FAILED to install new bindings." >&2
    echo "  There were none before, so nothing was lost." >&2
  elif mv "$backup" shared/types; then
    echo "generate-bindings: FAILED to install new bindings — restored the previous shared/types." >&2
  else
    # The backup lives inside $stage, so the EXIT trap would delete the only
    # surviving copy of the old bindings. Keep the staging tree instead.
    trap - EXIT
    echo "generate-bindings: FAILED to install new bindings, AND could not restore the previous copy." >&2
    echo "  The previous bindings are intact at:" >&2
    echo "    $backup" >&2
    echo "  Move that directory back to shared/types by hand. It is gitignored" >&2
    echo "  and has deliberately been left in place rather than cleaned up." >&2
  fi
  exit 1
fi
# Cleanup only. A failure here must not mask a swap that already succeeded —
# without the `|| true` it would trip `set -e` and report a good run as a bad
# one. The leftover is inside $stage, which the EXIT trap removes anyway.
if [[ -n "$backup" ]]; then
  rm -rf "$backup" || true
fi

count="$(find shared/types -name '*.ts' ! -name 'index.ts' -type f | wc -l | tr -d ' ')"
echo "Bindings generated. ${count} types exported."
